spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_order_system?createDatabaseIfNotExist = true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

server:
  port: 9091